version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.3.2 #
    container_name: mealie
    networks:
      proxy_default:
      mealie_default:
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.entryPoints: https
      traefik.http.services.traefik.loadbalancer.server.port: 9000
      traefik.http.routers.traefik.rule: Host(`meals.naibu.boerg.co`)
    deploy:
      resources:
        limits:
          memory: 1000M #
    depends_on:
      - postgres
    volumes:
      - ./mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.naibu.boerg.co
      # Database Settings
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=mealie
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    restart: always
  postgres:
    container_name: mealie-postgres
    image: postgres:15
    restart: always
    environment:
      # Database Settings
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=mealie
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    networks:
      mealie_default:
    volumes:
      - ./pgdata:/var/lib/postgresql/data
networks:
  proxy_default:
    external: true
  mealie_default: