services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    environment:
      GF_SERVER_ROOT_URL: https://warmind.naibu.boerg.co
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.entryPoints: https
      traefik.http.services.traefik.loadbalancer.server.port: 3000
      traefik.http.routers.traefik.rule: Host(`warmind.naibu.boerg.co`)
    user: '0'
    volumes:
      - './grafana-data:/var/lib/grafana'
    networks:
      grafana_default:
      proxy_default:

  loki:
    image: grafana/loki:2.9.2
    command: -config.file=/etc/loki/local-config.yaml
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.entryPoints: https
      traefik.http.services.traefik.loadbalancer.server.port: 3100
      traefik.http.routers.traefik.rule: Host(`loki.collectors.warmind.naibu.boerg.co`)
    volumes:
      - "./loki:/etc/loki"
    networks:
      grafana_default:
      proxy_default:

  alloy:
    image: grafana/alloy:latest
    volumes:
      - './alloy/alloy.conf:/etc/alloy/config.alloy'
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      grafana_default:
      proxy_default:

  blackbox:
    image: 'quay.io/prometheus/blackbox-exporter:latest'
    volumes:
      - './blackbox:/config'
    networks:
      grafana_default:
    command: ["--config.file=/config/blackbox.yml"]

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/prom/prom.yml'
    volumes:
      - './prom-data:/prom'
      - './prometheus:/prometheus'
    pid: host
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.entryPoints: https
      traefik.http.services.traefik.loadbalancer.server.port: 9090
      traefik.http.routers.traefik.rule: Host(`prometheus.collectors.warmind.naibu.boerg.co`)
    networks:
      grafana_default:
      proxy_default:
networks:
  grafana_default:
    driver: bridge
  proxy_default:
    external: true