services:
  adguard:
    image: adguard/adguardhome
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    labels:
      traefik.enable: true
      traefik.http.routers.adguard.entryPoints: https
      traefik.http.services.adguard.loadbalancer.server.port: 3000
      traefik.http.routers.adguard.rule: Host(`edguard.dublin.rodehack.net`)
    volumes:
      - ./work:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
networks:
  proxy_default:
    external: true
