name: "Build"
on:
  push:
    branches:
      - main
      - voyager
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: nix --version
      - run: which nix
      - uses: Svenum/attic-builder@ts-rewrite
        with:
          build_systems: true
          build_packages: false
          attic_url: "http://attic:8080"
          attic_cache: "boerg"
          attic_token: ${{ secrets.ATTIC_TOKEN }}
          dont_fail: false
          max_jobs: 2
          only_build_systems: nebula
          log_level: DEBUG
