name: "Build"
on:
  push:
    branches:
      - main
      - voyager
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: apt install sudo xz-utils tar udev jq -y
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      #- run: nix build --accept-flake-config .\#nixosConfigurations.izanami.config.system.build.toplevel --max-jobs 2
      #- run: rm -rf /homeless-shelter
      - run: rm -rf ~/.config/attic
      - uses: SirBerg/attic-builder@main
        with:
          build_systems: true
          build_packages: false
          attic_url: "http://attic:8080"
          attic_cache: "boerg"
          attic_token: ${{ secrets.ATTIC_TOKEN }}
          show_trace: true
          disable_nix_sandbox: true
      - run: nix log /nix/store/wl6h6gc4np4c2f6hym0y5fk3yyap40sn-multiviewer-for-f1-1.35.2.drv
