name: "Build"
on:
  push:
    branches:
      - main
      - voyager
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: export HOME="$TMP"
      - run: rm -rf /homeless-shelter
      - run: cat /etc/passwd
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: chmod -R +1777 ./*
      - run: useradd temp
      - run: su temp
      #- run: nix build --accept-flake-config .\#nixosConfigurations.izanami.config.system.build.toplevel --max-jobs 2
      #- run: rm -rf /homeless-shelter
      - uses: SirBerg/attic-builder@main
        with:
          build_systems: true
          build_packages: true
          attic_url: "https://cache.naibu.boerg.co"
          attic_cache: "boerg"
          attic_token: ${{ secrets.ATTIC_TOKEN }}
          show_trace: true
          disable_nix_sandbox: true
