name: "Build"
on:
  push:
    branches:
      - main
      - voyager
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: ls -la /
      - run: export HOME="$TMP"
      - run: rm /etc/bash.bashrc.backup-before-nix
      - run: rm -rf /homeless-shelter
      - run: curl -L https://nixos.org/nix/install | sh -s -- --daemon
      - run: while read -r env; do export "$env"; done
      - run: export HOME="$TMP"
      
      #- run: nix build --accept-flake-config .\#nixosConfigurations.izanami.config.system.build.toplevel --max-jobs 2
      #- run: rm -rf /homeless-shelter
      - uses: SirBerg/attic-builder@main
        with:
          build_systems: true
          build_packages: true
          attic_url: "https://cache.naibu.boerg.co"
          attic_cache: "boerg"
          attic_token: ${{ secrets.ATTIC_TOKEN }}
          show_trace: true
          disable_nix_sandbox: true
